#!/usr/bin/env bash

# Copyright 2019 Ray Holder
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly VERSION=1.1.0
readonly MEM_SLEEP=/sys/power/mem_sleep

function print_usage () {
  cat << EOF
Usage: laptop-sleep-tool [OPTION]

  View or update the current laptop sleep settings.

Options:
    -m,  --current-mem-sleep      Print the current mem_sleep state from /sys/power/mem_sleep
    -md, --set-mem-sleep-deep     Set the current mem_sleep state to "deep" (root only)
    -ms, --set-mem-sleep-s2idle   Set the current mem_sleep state to "s2idle" (root only)
    -v,  --version                Print the current version and exit
    -h,  --help                   Print this help text and exit

Examples:
  laptop-sleep-tool --current-mem-sleep
  laptop-sleep-tool --set-mem-sleep-deep

Report bugs and find the latest updates at https://github.com/rholder/laptop-sleep-tool.

EOF
}

function main () {
  case "$1" in
    -m|--current-mem-sleep)
      # Parse single line output from mem_sleep, like:
      # [s2idle] deep
      # into "s2idle"

      # spaces to newlines, lines with [, remove [ and ]
      cat ${MEM_SLEEP} | tr ' ' '\n' | grep '\[' | tr -d '[]'
    ;;
    -md|--set-mem-sleep-deep)
      echo "Setting current ${MEM_SLEEP} to:"
      echo deep | sudo tee ${MEM_SLEEP}
    ;;
    -ms|--set-mem-sleep-s2idle)
      echo "Setting current ${MEM_SLEEP} to:"
      echo s2idle | sudo tee ${MEM_SLEEP}
    ;;
    -v|--version)
      echo ${VERSION}
    ;;
    -|h--help)
      print_usage
    ;;
    *)
      # print usage and exit with an error by default
      print_usage
      exit 1
    ;;
  esac
}

main "$@"
